server:
  port: 8084

jwt:
  secretkey: GALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOTGALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOT

dgs:
  graphql:
    schema-locations:
      - classpath*:**/inventory/inventory-schema.graphql*


logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: catalog
  cloud:
    config:
      uri : http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
    metrics:
      distributions:
        percentiles:
          http.server.requests: 0.5, 0.75, 0.95, 0.98, 1.0
          method.requests: 0.5, 0.75, 0.95, 0.98, 1.0
      tags:
        applications: ${spring.application.name}


