server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secretkey: GALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOTGALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOT

dgs:
  graphql:
    schema-locations:
      - classpath*:**/auth/auth-schema.graphql*


