server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secretkey: pranetr1456KEYROCKSSUPERMARIO123KEYS789HELPSALOTpranetr1456KEYROCKSSUPERMARIO123KEYS789HELPSALOT

dgs:
  graphql:
    schema-locations:
      - classpath*:**/auth/auth-schema.graphql*


